
export enum Screen {
  LANDING = 'LANDING',
  SIGNUP_STEP_1 = 'SIGNUP_STEP_1',
  SIGNUP_STEP_2 = 'SIGNUP_STEP_2',
  DASHBOARD = 'DASHBOARD',
  SCHOLARSHIPS = 'SCHOLARSHIPS',
  JOBS = 'JOBS',
  CV_ATS = 'CV_ATS',
  COVER_LETTER = 'COVER_LETTER',
  PRESENTATION = 'PRESENTATION',
  LEARNING_PLAN = 'LEARNING_PLAN',
  PLAGIARISM = 'PLAGIARISM',
  FINANCE = 'FINANCE',
  HABIT_TRACKER = 'HABIT_TRACKER',
  COMMUNITY = 'COMMUNITY',
  CONTACT = 'CONTACT',
  SIGN_IN = 'SIGN_IN',
  BLOG = 'BLOG',
  ABOUT = 'ABOUT',
  PROFILE = 'PROFILE',
  // Admin Screens
  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  ADMIN_EMPLOYERS = 'ADMIN_EMPLOYERS',
  ADMIN_PRICING = 'ADMIN_PRICING',
  ADMIN_USERS = 'ADMIN_USERS',
  ADMIN_SCHOLARSHIPS = 'ADMIN_SCHOLARSHIPS',
  ADMIN_ROLES = 'ADMIN_ROLES',
  ADMIN_BLOG = 'ADMIN_BLOG',
  ADMIN_SETTINGS = 'ADMIN_SETTINGS',
  // Employer Screens
  EMPLOYER_DASHBOARD = 'EMPLOYER_DASHBOARD'
}

export interface NavigationProps {
  navigateTo: (screen: Screen) => void;
}
